### PR TITLE
refactor slackbot class to make it easier to test

### PR DESCRIPTION
**Pull request by jotok**
By making the actual slack rtm and web clients parameters to the Slackbot class, we can mock them for testing.

### CODE REVIEW

**Comment by zetlen** [comment]
This is good and robust code. I'm inclined to merge it and I get how it isolates our own implementation for testing. My move would have been to mock the http transport from the outside using `nock`, but I know that that kind of mocking is an antipattern and I would just be lazy. So I appreciate that you showed the actual DI approach here; however, I think it kinda makes instantiation too verbose. 

To combat verbosity, I think you can make a couple of extra assumptions that reduce boilerplate.
 - arguments to the clients will remain constant and consist of env vars
 - the Slackbot will always require a WebClient and an RtmClient
 - there is no test case that requires different environments for the WebClient and the RtmClient
 - logging verbosity and therefore logger instantiation can be pulled entirely out of the slackbox itself

So I think we can come up with a `SlackbotTransports` type, an object with `WebClient` and `RtmClient` properties that are constructors accepting a `token` and an `options` dictionary. I like this type definition because `@slack/client` happens to fit it. We have the freedom to build mock transports that fit that type. So here's what I'm thinking. The constructor starts like this:

```js
function Slackbot (transports, env, logger, clientOpts, webOpts) {
  var defaultOpts = env.isProd ? {} : { logLevel: 'verbose' };
  var clientOpts = opts ? defaultOpts : assign(defaultOpts, opts);
  var rtm = new transports.RtmClient(env.vars.SLACK_TOKEN, clientOpts);
  var web = new transports.WebClient(env.vars.SLACK_TOKEN, webOpts || clientOpts);
[...]
```

Then you can call it like this:
```js
var env = getEnv(process);
var bot = Slackbot(
  require('@slack/client'),
  env,
  helpers.logger('Slackbot', env.isDev),
  { logLevel: env.isDev ? 'verbose' : 'error' }
);
```

Feels a little nicer to me, because it makes what I think are the safe assumptions and maintains full testability.

Thanks again for trying to encapsulate this stuff better.

**Comment by jotok** [comment]
Thanks James! I like passing transport as the constructor argument. My personal preference is to use explicit constructor arguments (e.g., slack_token) until the number of arguments becomes unwieldy, and then to fall back on configuration objects, but this may be more of a virtue in statically typed languages. I'm willing to defer on this point if passing in env is a common practice. 

Do you think we need two options arguments, or was that a goof? I think it can be useful to separate configurations for different aspects of the app, but I don't think there are currently enough options to warrant it.

**Comment by zetlen** [comment]
Nah, we don't need two options arguments. I looked at the way the node Slack SDK stubs itself for testing, and there are some undocumented config options you can use when mocking webdocket requests. But with your way, we don't need to mock that anyway.

I don't think that positional arguments versus configuration objects matters that much for DI, but positional arguments can be hard to remember in a language where you rarely get intelligent code completion. Configuration objects are a very common practice as a result--it's a way of getting named parameters.

**Comment by jotok** [comment]
I'm going to make the suggested changes, but I can't help myself from continuing the positional arguments versus configuration object debate. I'm totally on board with named arguments, and if the intended usage of a configuration object is to be a stand in for named arguments (i.e., the configuration object is created inline when the function is invoked) then that seems fine. My arguments are that positional/named arguments improve code readability, and all things being equal it's better that function behavior doesn't depend on global application state.

To the first point, the extreme case of what I'm talking about is that it is much harder to read code that looks like
    var result = x.process(opts);
than
    var dinner = restaurant.prepare(item = 'lobster', wine = true);
Especially if `opts` was defined far away from the method call site. Configuration objects are a step in the direction of the first example. In addition, if you have one omnibus configuration object that gets passed to several methods, you start having to look at the source to be sure that changing one option won't change the behavior of the method.

That last bit kind of gets at my second point, which is just that I think it's better if method behavior can be determined at the call site. Passing environment into a method call seems like it could bite you if your environment changes in an unexpected way. In your example above, I would prefer to see
    helpers.logger({ logLevel: 'debug' });
instead
    helpers.logger({ isDev: true });
because I can tell what the first method call is doing without checking the docs or source code.

**Comment by zetlen** [comment]
That's absolutely fair. I'm not a big fan of my `getEnv` implementation anyway--it just was a way to get a bunch of boilerplate out of the way while I worked. We can replace it with explicit token passing if we want.

You can get a combination of call-site readability and code reuse if you switch to ES6 and object destructuring/constructing sugar. Then you can get:
```js
import { WebClient, RtmClient } from '@slack/client'; // destructured bindings
const { isDev, vars } = getEnv(process); // destructured object
const bot = Slackbot(
  { WebClient, RtmClient }, // at runtime this just becomes a transports object
  { isDev, vars: { SLACK_TOKEN: vars.SLACK_TOKEN }, // same here with the env object
  helpers.logger('Slackbot', { logLevel: isDev ? 'verbose' : 'error' })
);
```

**Comment by jotok** [comment]
I've implemented your suggestions and I think it looks a lot nicer. I took the logger out of the constructor because upon further reflection I don't think we to test our logging calls.

Also, I've thought about it more and I think you could make a case that it makes sense for a logger to depend on environment, so that wasn't a good example.

**Comment by zetlen** [comment]
Looks great. Last thing: can you change the `module.exports` of `slackbot.js` so that it just directly exports the Slackbot factory like before?

**Comment by jotok** [comment]
Done!

**Comment by zetlen** [comment]
🎂

**Pull request merged**
